version: "3.8"

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: luanny12
      POSTGRES_DB: alura-receita
    ports:
      - "5432:5432"
